In [72]:
import pandas as pd
import numpy as np
import chardet

# Preprocessing

In [2]:
# Check the encoding of the CSV file 

with open('2022 Lourdes Mens Elite Times.csv', 'rb') as file:
    result = chardet.detect(file.read())
    
print(result['encoding'])

Windows-1252

In [3]:
# Import the csv file using pandas read_csv() method

race_times_raw_data = pd.read_csv('2022 Lourdes Mens Elite Times.csv', encoding='windows-1252')
race_times_raw_data

,Position,World Ranking,Name,Team,UCI Number,Nationality,YOB,Speed,Speed Ranking,Split 1,Split 1 pos,Split 2,Split 2 pos,Split 3,Split 3 pos,Split 4,Split 4 pos,Time,TOW,Points
0,1,6,IERRON Amaury,COMMENCAL/MUC-OFF BY RIDING,10008827283,FRA,1996,60.335,11,0:44.269,1,1:17.360,7,1:53.519,1,2:20.293,1,02:47.0,0.000000,200
1,2,14,ILES Finn,SPECIALIZED GRAVITY,10090907774,CAN,1999,59.081,21,0:44.924,2,1:16.398,1,1:53.573,2,2:20.354,2,02:48.0,0.847000,160
2,3,1,BRUNI Loic,SPECIALIZED GRAVITY,10007544358,FRA,1994,58.824,25,0:45.023,4,1:16.676,3,1:53.788,3,2:20.960,3,02:48.0,1.086000,140
3,4,8,COULANGES Benoit,DORVAL AM COMMENCAL,10008194359,FRA,1994,59.081,21,0:45.302,7,1:16.893,5,1:54.638,6,2:21.349,4,02:49.0,1.466000,125
4,5,17,SHAW Luca,CANYON COLLECTIVE FACTORY TEAM,10008813442,USA,1996,61.224,3,0:45.223,6,1:16.795,4,1:54.231,4,2:21.860,5,02:50.0,2.431000,110
5,6,9,HART Danny,CUBE FACTORY RACING,10005470073,GBR,1991,60.067,14,0:46.511,21,1:18.379,12,1:54.979,7,2:22.370,6,02:50.0,2.695000,95
6,7,5,WILSON Reece,TREK FACTORY RACING DH,10009563271,GBR,1996,60.335,11,0:45.689,9,1:17.073,6,1:54.377,5,2:22.392,7,02:51.0,3.373000,90
7,8,7,GREENLAND Laurie,SANTA CRUZ SYNDICATE,10009404738,GBR,1997,58.127,36,0:45.453,8,1:18.220,9,1:56.086,8,2:23.325,8,02:51.0,3.856000,85
8,9,64,VIDAL Antoine,COMMENCAL LES ORRES,10070590924,FRA,2001,57.878,40,0:46.027,14,1:18.853,15,1:56.199,9,2:23.371,9,02:51.0,4.160000,80
9,10,1,WALKER Matt,MADISON SARACEN FACTORY TEAM,10011016756,GBR,1999,61.714,2,0:46.072,15,1:18.374,11,1:56.357,10,2:23.966,10,02:52.0,4.463000,75
10,11,1,NORTON Dakotah,INTENSE FACTORY RACING,10010038167,USA,1992,61.155,4,0:46.652,23,1:19.716,21,1:57.219,12,2:24.453,11,02:52.0,5.219000,70
11,12,3,VERGIER Loris,TREK FACTORY RACING DH,10008723112,FRA,1996,59.081,21,0:45.003,3,1:16.399,2,1:57.561,14,2:24.706,12,02:53.0,5.414000,65
12,13,30,EDWARDS Kade,TREK FACTORY RACING DH,10023896336,GBR,2000,58.065,38,0:47.053,34,1:19.796,24,1:58.072,18,2:26.002,15,02:54.0,6.362000,60
13,14,1,SUAREZ ALONSO Ange,COMMENCAL / 100%,10008831529,ESP,1995,58.315,33,0:46.381,19,1:19.222,17,1:57.803,16,2:25.928,14,02:54.0,6.561000,55
14,15,2,HARTENSTERN Max,CUBE FACTORY RACING,10011213584,GER,1999,59.276,20,0:45.839,11,1:18.516,13,1:57.233,13,2:25.913,13,02:54.0,6.851000,50
15,16,1,MINNAAR Greg,SANTA CRUZ SYNDICATE,10002818640,RSA,1981,58.315,33,0:45.994,13,1:19.277,19,1:57.850,17,2:26.252,16,02:55.0,7.456000,45
16,17,109,FRIXTALON Hugo,COMMENCAL / 100%,10016018118,FRA,1999,58.065,38,0:46.739,27,1:19.186,16,1:56.962,11,2:26.290,17,02:55.0,7.665000,44
17,18,1,TRUMMER David,MS MONDRAKER TEAM,10007713403,AUT,1994,58.824,25,0:46.632,22,1:19.852,25,1:58.839,26,2:26.901,20,02:55.0,7.734000,43
18,19,93,VERNON Taylor,SORTED RACEGEAR,10008728667,GBR,1996,56.426,51,0:47.705,48,1:21.562,43,1:59.479,27,2:27.393,24,02:55.0,8.010000,42
19,20,22,KERR Bernard,PIVOT FACTORY RACING,10006413094,GBR,1991,58.824,25,0:46.435,20,1:18.632,14,1:57.740,15,2:26.432,18,02:55.0,8.159000,41
20,21,53,MEIER-SMITH Luke,PROPAIN FACTORY RACING,10049212326,AUS,2002,60.403,10,0:46.984,30,1:20.048,27,1:58.301,20,2:26.836,19,02:55.0,8.219000,40
21,22,21,KOLB Andreas,CONTINENTAL ATHERTON,10009187092,AUT,1996,58.568,31,0:46.994,32,1:19.757,23,1:58.658,23,2:26.971,22,02:56.0,8.311000,39
22,23,23,HATTON Charlie,CONTINENTAL ATHERTON,10009897014,GBR,1998,57.878,40,0:46.661,24,1:19.947,26,1:58.645,22,2:26.911,21,02:56.0,8.513000,38
23,24,1,IERRON Baptiste,DORVAL AM COMMENCAL,10008586504,FRA,1993,56.191,53,0:47.016,33,1:19.744,22,1:58.813,25,2:27.133,23,02:56.0,9.122000,37
24,25,31,LEVESQUE Dylan,SCOTT DOWNHILL FACTORY,10008831731,FRA,1996,59.801,18,0:45.933,12,1:19.227,18,1:58.417,21,2:27.941,27,02:56.0,9.261000,36
25,26,24,LUCAS Dean,SCOTT DOWNHILL FACTORY,10008103322,AUS,1995,60.674,7,0:45.815,10,1:18.242,10,1:58.784,24,2:27.890,25,02:57.0,9.347000,35
26,27,40,DICKSON Jacob,MS MONDRAKER TEAM,10009453642,IRL,1997,60.067,14,0:47.191,38,1:21.043,34,1:59.984,30,2:28.116,28,02:57.0,9.422000,34
27,28,51,ESTAQUE Thomas,COMMENCAL / 100%,10008848505,FRA,1996,58.824,25,0:47.198,39,1:20.324,29,1:59.502,28,2:28.182,29,02:57.0,9.605000,33
28,29,43,FEARON Connor,FORBIDDEN SYNTHESIS TEAM,10007656314,AUS,1994,60.606,9,0:46.284,17,1:19.309,20,1:58.299,19,2:27.924,26,02:57.0,9.843000,32
29,30,118,CABIROU Rudy,NaN,10007714413,FRA,1994,61.998,1,0:46.685,25,1:20.823,32,2:00.185,33,2:28.697,32,02:57.0,9.939000,31
30,31,97,LUFFMAN Dennis,CANYON COLLECTIVE FMD,10061876381,GBR,2003,58.127,36,0:46.905,28,1:20.516,30,1:59.874,29,2:28.425,30,02:57.0,9.941000,30
31,32,143,DAILLY Adrien,NaN,10009562968,FRA,1996,59.081,21,0:47.240,41,1:21.300,38,2:00.001,31,2:28.447,31,02:57.0,9.990000,29
32,33,75,GWIN Aaron,INTENSE FACTORY RACING,10006516663,USA,1987,60.879,6,0:46.912,29,1:20.976,33,2:00.193,34,2:28.752,33,02:57.0,10.084000,28
33,34,1,THIRION R‚mi,GIANT FACTORY OFF - ROAD TEAM,10005415715,FRA,1990,58.568,31,0:47.909,52,1:21.235,35,2:00.827,39,2:28.808,34,02:57.0,10.144000,27
34,35,145,REVELLI Loris,CANYON COLLECTIVE PIRELLI,10009443942,ITA,1997,60.067,14,0:47.543,46,1:21.572,44,2:00.660,37,2:29.293,36,02:57.0,10.196000,26
35,36,102,CHAELET Simon,NaN,10071553749,FRA,2002,61.155,4,0:47.759,49,1:21.366,40,2:00.786,38,2:29.685,38,02:58.0,10.959000,25
36,37,92,VIEIRA Roger,NaN,10009164258,BRA,1994,57.816,43,0:47.577,47,1:21.438,42,2:00.026,32,2:29.163,35,02:58.0,10.960000,24
37,38,35,WILLIAMSON Greg,COMMENCAL / 100%,10006909111,GBR,1992,58.824,25,0:47.480,45,1:21.673,46,2:01.617,45,2:30.070,40,02:58.0,11.148000,23
38,39,89,O CALLAGHAN Oisin,YT RACING DUDES,10017486353,IRL,2003,56.902,49,0:47.354,42,1:21.340,39,2:01.237,41,2:29.612,37,02:58.0,11.257000,22
39,40,1,WALLACE Mark,CANYON COLLECTIVE FACTORY TEAM,10008172636,CAN,1995,58.315,33,0:47.810,50,1:21.429,41,2:01.158,40,2:29.748,39,02:59.0,11.358000,21
40,41,27,MACDONALD Brook,MS MONDRAKER TEAM,10006429969,NZL,1991,59.801,18,0:46.988,31,1:20.185,28,2:00.594,36,2:30.234,41,02:59.0,11.801000,20
41,42,45,DOOLEY Austin,COMMENCAL NORTH AMERICA,10087908151,USA,2002,56.426,51,0:47.477,44,1:21.947,47,2:01.415,42,2:30.993,44,02:59.0,12.282000,19
42,43,71,ROGGE Antoine,NaN,10078163590,FRA,2002,57.569,47,0:47.060,35,1:22.101,48,2:01.552,43,2:30.716,43,03:00.0,12.389000,18
43,44,37,SLACK Dan,SR SUNTOUR COMMENCAL BY GRAVITY,10088103464,GBR,2002,57.878,40,0:47.388,43,1:21.623,45,2:01.591,44,2:30.696,42,03:00.0,12.630000,17
44,45,41,SILVA Dante,CANYON COLLECTIVE PIRELLI,10071893653,USA,2002,58.824,25,0:47.133,37,1:21.267,36,2:02.524,48,2:32.376,49,03:00.0,13.228000,16
45,46,50,GARCIN Johan,VVRACING ACADEMY,10056657377,FRA,2002,57.816,43,0:49.074,56,1:22.904,50,2:02.469,47,2:31.766,46,03:01.0,13.567000,15
46,47,55,LALY Thibault,PINKBIKE RACING,10009533464,FRA,1997,60.674,7,0:48.082,53,1:22.150,49,2:01.930,46,2:31.305,45,03:01.0,13.723000,14
47,48,54,MASTERS Edward,PIVOT FACTORY RACING,10005560003,NZL,1989,60.134,13,0:48.935,55,1:23.718,53,2:02.880,49,2:32.162,47,03:01.0,13.873000,13
48,49,125,GIRONDE Mael,NaN,10074421616,FRA,2003,55.498,55,0:47.858,51,1:22.914,51,2:03.194,51,2:32.554,51,03:01.0,14.152000,12
49,50,62,BARANEK Rastislav,NaN,10008169808,SVK,1995,57.816,43,0:48.528,54,1:23.041,52,2:02.993,50,2:32.254,48,03:02.0,14.860000,11
50,51,126,READING Jack,SR SUNTOUR COMMENCAL BY GRAVITY,10006576176,GBR,1988,56.902,49,0:51.154,57,1:24.890,54,2:06.334,53,2:37.178,53,03:07.0,19.842000,10
51,52,44,EDMONDSON Jamie,ROCKSHOX TREK RACE TEAM,10023865620,GBR,2001,57.631,46,0:47.074,36,1:27.055,56,2:08.179,54,2:38.636,54,03:08.0,20.973000,9
52,53,121,MAES Martin,NaN,10009453945,BEL,1997,60.067,14,1:04.472,59,1:38.508,57,2:16.784,55,2:44.163,55,03:12.0,24.660000,8
53,54,28,ALAZZARI Davide,RRT ROGUE RACING - AFTER SKULL TEAM,10010022205,ITA,1995,56.191,53,1:06.195,60,1:40.802,58,2:20.699,56,2:49.957,56,03:19.0,31.981000,7
54,55,63,BANDEIRA Gon‡alo,NaN,10054661096,POR,2002,54.878,56,0:46.359,18,1:21.297,37,2:24.409,57,2:53.155,57,03:24.0,36.515000,6
55,56,69,MENOYO BUSQUETS au,COMMENCAL - SCHWALBE,10079233725,ESP,2003,30.647,60,0:47.228,40,1:20.600,31,2:00.486,35,2:32.478,50,03:25.0,37.475000,5
56,57,39,KERR Henry,PROPAIN FACTORY RACING,10111341129,IRL,2000,48.693,59,0:46.709,26,1:26.375,55,2:04.920,52,2:34.823,52,03:26.0,38.292000,4
57,58,34,HARRISON Charlie,TREK FACTORY RACING DH,10009645925,USA,1997,57.143,48,0:46.186,16,1:46.648,60,2:26.940,59,2:56.576,58,03:26.0,39.100000,3
58,59,2,DAPRELA Thibaut,COMMENCAL/MUC-OFF BY RIDING,10072798480,FRA,2001,52.529,57,0:45.056,5,1:17.761,8,2:25.252,58,3:08.088,59,03:44.0,56.873000,2
59,60,60,FAIRCLOUGH Brendan,SCOTT DOWNHILL FACTORY,10003642635,GBR,1988,49.180,58,0:52.845,58,1:43.444,59,2:46.689,60,3:37.291,60,04:15.0,0.001016,1

In [4]:
# View the data types of each column

race_times_raw_data.dtypes

Position           int64
World Ranking      int64
Name              object
Team              object
UCI Number         int64
Nationality       object
YOB                int64
Speed            float64
Speed Ranking      int64
Split 1           object
Split 1 pos        int64
Split 2           object
Split 2 pos        int64
Split 3           object
Split 3 pos        int64
Split 4           object
Split 4 pos        int64
Time              object
TOW              float64
Points             int64
dtype: object

In [54]:
# Create a new variable that replicates the original data set, leaving the original import un processed for later reference

race_times = race_times_raw_data.copy()

In [55]:
race_times.describe(include='all')

,Position,World Ranking,Name,Team,UCI Number,Nationality,YOB,Speed,Speed Ranking,Split 1,Split 1 pos,Split 2,Split 2 pos,Split 3,Split 3 pos,Split 4,Split 4 pos,Time,TOW,Points
count,60.000000,60.00000,60,51,6.000000e+01,60,60.000000,60.000000,60.000000,60,60.000000,60,60.000000,60,60.000000,60,60.000000,60,60.000000,60.000000
unique,NaN,NaN,60,29,NaN,16,NaN,NaN,NaN,60,NaN,60,NaN,60,NaN,60,NaN,25,NaN,NaN
top,NaN,NaN,IERRON Amaury,COMMENCAL / 100%,NaN,FRA,NaN,NaN,NaN,0:44.269,NaN,1:17.360,NaN,1:53.519,NaN,2:20.293,NaN,02:57.0,NaN,NaN
freq,NaN,NaN,1,4,NaN,18,NaN,NaN,NaN,1,NaN,1,NaN,1,NaN,1,NaN,10,NaN,NaN
mean,30.500000,45.55000,NaN,NaN,1.002561e+10,NaN,1996.383333,57.900883,29.733333,NaN,30.500000,NaN,30.500000,NaN,30.500000,NaN,30.500000,NaN,12.160734,41.583333
std,17.464249,40.98343,NaN,NaN,2.978446e+07,NaN,4.679894,4.354411,17.561385,NaN,17.464249,NaN,17.464249,NaN,17.464249,NaN,17.464249,NaN,10.786813,40.167991
min,1.000000,1.00000,NaN,NaN,1.000282e+10,NaN,1981.000000,30.647000,1.000000,NaN,1.000000,NaN,1.000000,NaN,1.000000,NaN,1.000000,NaN,0.000000,1.000000
25%,15.750000,7.75000,NaN,NaN,1.000815e+10,NaN,1994.000000,57.769750,14.000000,NaN,15.750000,NaN,15.750000,NaN,15.750000,NaN,15.750000,NaN,6.778500,15.750000
50%,30.500000,38.00000,NaN,NaN,1.000945e+10,NaN,1996.000000,58.696000,28.000000,NaN,30.500000,NaN,30.500000,NaN,30.500000,NaN,30.500000,NaN,9.891000,30.500000
75%,45.250000,65.25000,NaN,NaN,1.003023e+10,NaN,2000.250000,60.067000,43.750000,NaN,45.250000,NaN,45.250000,NaN,45.250000,NaN,45.250000,NaN,12.779500,46.250000
max,60.000000,145.00000,NaN,NaN,1.011134e+10,NaN,2003.000000,61.998000,60.000000,NaN,60.000000,NaN,60.000000,NaN,60.000000,NaN,60.000000,NaN,56.873000,200.000000

In [56]:
# Check the names of columns are correctly stored

race_times.columns.array

<PandasArray>
[     'Position', 'World Ranking',          'Name',          'Team',
    'UCI Number',   'Nationality',           'YOB',         'Speed',
 'Speed Ranking',       'Split 1',   'Split 1 pos',       'Split 2',
   'Split 2 pos',       'Split 3',   'Split 3 pos',       'Split 4',
   'Split 4 pos',          'Time',           'TOW',        'Points']
Length: 20, dtype: object

In [57]:
# Remove blank spaces from titles that have them

race_times.rename(columns=lambda x: x.strip().lower().replace(' ','_'), inplace=True)

In [58]:
# Check titles are correct

race_times.columns.array

<PandasArray>
[     'position', 'world_ranking',          'name',          'team',
    'uci_number',   'nationality',           'yob',         'speed',
 'speed_ranking',       'split_1',   'split_1_pos',       'split_2',
   'split_2_pos',       'split_3',   'split_3_pos',       'split_4',
   'split_4_pos',          'time',           'tow',        'points']
Length: 20, dtype: object

In [59]:
# Check for unique values in 'position' - this column shows the racers position in the race and is unique for each racer

race_times['position'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60], dtype=int64)

In [60]:
# Change 'position' data type to a string variable instead on an int

race_times['position'] = race_times['position'].astype(str)

In [61]:
# Check for unqique values in 'name'

race_times['name'].unique()

# The names here are in a confusing format, standarise them and create seperate columns for first and last name
# Unsure if this is useful to keep them seperate at this stage

array(['IERRON Amaury', 'ILES Finn', 'BRUNI Loic', 'COULANGES Benoit',
       'SHAW Luca', 'HART Danny', 'WILSON Reece', 'GREENLAND Laurie',
       'VIDAL Antoine', 'WALKER Matt', 'NORTON Dakotah', 'VERGIER Loris',
       'EDWARDS Kade', 'SUAREZ ALONSO Ange', 'HARTENSTERN Max',
       'MINNAAR Greg', 'FRIXTALON Hugo', 'TRUMMER David', 'VERNON Taylor',
       'KERR Bernard', 'MEIER-SMITH Luke', 'KOLB Andreas',
       'HATTON Charlie', 'IERRON Baptiste', 'LEVESQUE Dylan',
       'LUCAS Dean', 'DICKSON Jacob', 'ESTAQUE Thomas', 'FEARON Connor',
       'CABIROU Rudy', 'LUFFMAN Dennis', 'DAILLY Adrien', 'GWIN Aaron',
       'THIRION R‚mi', 'REVELLI Loris', 'CHAELET Simon', 'VIEIRA Roger',
       'WILLIAMSON Greg', 'O CALLAGHAN Oisin', 'WALLACE Mark',
       'MACDONALD Brook', 'DOOLEY Austin', 'ROGGE Antoine', 'SLACK Dan',
       'SILVA Dante', 'GARCIN Johan', 'LALY Thibault', 'MASTERS Edward',
       'GIRONDE Mael', 'BARANEK Rastislav', 'READING Jack',
       'EDMONDSON Jamie', 'MAES Martin', 'ALAZZARI Davide',
       'BANDEIRA Gon‡alo', 'MENOYO BUSQUETS au', 'KERR Henry',
       'HARRISON Charlie', 'DAPRELA Thibaut', 'FAIRCLOUGH Brendan'],
      dtype=object)

In [63]:
# Split strings in column 'name' and store first and last name in seperate columns

race_times[['last_name', 'first_name']] = race_times['name'].str.split(' ', 1, expand=True)

race_times

C:\Users\User\AppData\Local\Temp\ipykernel_7744\1607777744.py:3: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  race_times[['last_name', 'first_name']] = race_times['name'].str.split(' ', 1, expand=True)

,position,world_ranking,name,team,uci_number,nationality,yob,speed,speed_ranking,split_1,...,split_2_pos,split_3,split_3_pos,split_4,split_4_pos,time,tow,points,last_name,first_name
0,1,6,IERRON Amaury,COMMENCAL/MUC-OFF BY RIDING,10008827283,FRA,1996,60.335,11,0:44.269,...,7,1:53.519,1,2:20.293,1,02:47.0,0.000000,200,IERRON,Amaury
1,2,14,ILES Finn,SPECIALIZED GRAVITY,10090907774,CAN,1999,59.081,21,0:44.924,...,1,1:53.573,2,2:20.354,2,02:48.0,0.847000,160,ILES,Finn
2,3,1,BRUNI Loic,SPECIALIZED GRAVITY,10007544358,FRA,1994,58.824,25,0:45.023,...,3,1:53.788,3,2:20.960,3,02:48.0,1.086000,140,BRUNI,Loic
3,4,8,COULANGES Benoit,DORVAL AM COMMENCAL,10008194359,FRA,1994,59.081,21,0:45.302,...,5,1:54.638,6,2:21.349,4,02:49.0,1.466000,125,COULANGES,Benoit
4,5,17,SHAW Luca,CANYON COLLECTIVE FACTORY TEAM,10008813442,USA,1996,61.224,3,0:45.223,...,4,1:54.231,4,2:21.860,5,02:50.0,2.431000,110,SHAW,Luca
5,6,9,HART Danny,CUBE FACTORY RACING,10005470073,GBR,1991,60.067,14,0:46.511,...,12,1:54.979,7,2:22.370,6,02:50.0,2.695000,95,HART,Danny
6,7,5,WILSON Reece,TREK FACTORY RACING DH,10009563271,GBR,1996,60.335,11,0:45.689,...,6,1:54.377,5,2:22.392,7,02:51.0,3.373000,90,WILSON,Reece
7,8,7,GREENLAND Laurie,SANTA CRUZ SYNDICATE,10009404738,GBR,1997,58.127,36,0:45.453,...,9,1:56.086,8,2:23.325,8,02:51.0,3.856000,85,GREENLAND,Laurie
8,9,64,VIDAL Antoine,COMMENCAL LES ORRES,10070590924,FRA,2001,57.878,40,0:46.027,...,15,1:56.199,9,2:23.371,9,02:51.0,4.160000,80,VIDAL,Antoine
9,10,1,WALKER Matt,MADISON SARACEN FACTORY TEAM,10011016756,GBR,1999,61.714,2,0:46.072,...,11,1:56.357,10,2:23.966,10,02:52.0,4.463000,75,WALKER,Matt
10,11,1,NORTON Dakotah,INTENSE FACTORY RACING,10010038167,USA,1992,61.155,4,0:46.652,...,21,1:57.219,12,2:24.453,11,02:52.0,5.219000,70,NORTON,Dakotah
11,12,3,VERGIER Loris,TREK FACTORY RACING DH,10008723112,FRA,1996,59.081,21,0:45.003,...,2,1:57.561,14,2:24.706,12,02:53.0,5.414000,65,VERGIER,Loris
12,13,30,EDWARDS Kade,TREK FACTORY RACING DH,10023896336,GBR,2000,58.065,38,0:47.053,...,24,1:58.072,18,2:26.002,15,02:54.0,6.362000,60,EDWARDS,Kade
13,14,1,SUAREZ ALONSO Ange,COMMENCAL / 100%,10008831529,ESP,1995,58.315,33,0:46.381,...,17,1:57.803,16,2:25.928,14,02:54.0,6.561000,55,SUAREZ,ALONSO Ange
14,15,2,HARTENSTERN Max,CUBE FACTORY RACING,10011213584,GER,1999,59.276,20,0:45.839,...,13,1:57.233,13,2:25.913,13,02:54.0,6.851000,50,HARTENSTERN,Max
15,16,1,MINNAAR Greg,SANTA CRUZ SYNDICATE,10002818640,RSA,1981,58.315,33,0:45.994,...,19,1:57.850,17,2:26.252,16,02:55.0,7.456000,45,MINNAAR,Greg
16,17,109,FRIXTALON Hugo,COMMENCAL / 100%,10016018118,FRA,1999,58.065,38,0:46.739,...,16,1:56.962,11,2:26.290,17,02:55.0,7.665000,44,FRIXTALON,Hugo
17,18,1,TRUMMER David,MS MONDRAKER TEAM,10007713403,AUT,1994,58.824,25,0:46.632,...,25,1:58.839,26,2:26.901,20,02:55.0,7.734000,43,TRUMMER,David
18,19,93,VERNON Taylor,SORTED RACEGEAR,10008728667,GBR,1996,56.426,51,0:47.705,...,43,1:59.479,27,2:27.393,24,02:55.0,8.010000,42,VERNON,Taylor
19,20,22,KERR Bernard,PIVOT FACTORY RACING,10006413094,GBR,1991,58.824,25,0:46.435,...,14,1:57.740,15,2:26.432,18,02:55.0,8.159000,41,KERR,Bernard
20,21,53,MEIER-SMITH Luke,PROPAIN FACTORY RACING,10049212326,AUS,2002,60.403,10,0:46.984,...,27,1:58.301,20,2:26.836,19,02:55.0,8.219000,40,MEIER-SMITH,Luke
21,22,21,KOLB Andreas,CONTINENTAL ATHERTON,10009187092,AUT,1996,58.568,31,0:46.994,...,23,1:58.658,23,2:26.971,22,02:56.0,8.311000,39,KOLB,Andreas
22,23,23,HATTON Charlie,CONTINENTAL ATHERTON,10009897014,GBR,1998,57.878,40,0:46.661,...,26,1:58.645,22,2:26.911,21,02:56.0,8.513000,38,HATTON,Charlie
23,24,1,IERRON Baptiste,DORVAL AM COMMENCAL,10008586504,FRA,1993,56.191,53,0:47.016,...,22,1:58.813,25,2:27.133,23,02:56.0,9.122000,37,IERRON,Baptiste
24,25,31,LEVESQUE Dylan,SCOTT DOWNHILL FACTORY,10008831731,FRA,1996,59.801,18,0:45.933,...,18,1:58.417,21,2:27.941,27,02:56.0,9.261000,36,LEVESQUE,Dylan
25,26,24,LUCAS Dean,SCOTT DOWNHILL FACTORY,10008103322,AUS,1995,60.674,7,0:45.815,...,10,1:58.784,24,2:27.890,25,02:57.0,9.347000,35,LUCAS,Dean
26,27,40,DICKSON Jacob,MS MONDRAKER TEAM,10009453642,IRL,1997,60.067,14,0:47.191,...,34,1:59.984,30,2:28.116,28,02:57.0,9.422000,34,DICKSON,Jacob
27,28,51,ESTAQUE Thomas,COMMENCAL / 100%,10008848505,FRA,1996,58.824,25,0:47.198,...,29,1:59.502,28,2:28.182,29,02:57.0,9.605000,33,ESTAQUE,Thomas
28,29,43,FEARON Connor,FORBIDDEN SYNTHESIS TEAM,10007656314,AUS,1994,60.606,9,0:46.284,...,20,1:58.299,19,2:27.924,26,02:57.0,9.843000,32,FEARON,Connor
29,30,118,CABIROU Rudy,NaN,10007714413,FRA,1994,61.998,1,0:46.685,...,32,2:00.185,33,2:28.697,32,02:57.0,9.939000,31,CABIROU,Rudy
30,31,97,LUFFMAN Dennis,CANYON COLLECTIVE FMD,10061876381,GBR,2003,58.127,36,0:46.905,...,30,1:59.874,29,2:28.425,30,02:57.0,9.941000,30,LUFFMAN,Dennis
31,32,143,DAILLY Adrien,NaN,10009562968,FRA,1996,59.081,21,0:47.240,...,38,2:00.001,31,2:28.447,31,02:57.0,9.990000,29,DAILLY,Adrien
32,33,75,GWIN Aaron,INTENSE FACTORY RACING,10006516663,USA,1987,60.879,6,0:46.912,...,33,2:00.193,34,2:28.752,33,02:57.0,10.084000,28,GWIN,Aaron
33,34,1,THIRION R‚mi,GIANT FACTORY OFF - ROAD TEAM,10005415715,FRA,1990,58.568,31,0:47.909,...,35,2:00.827,39,2:28.808,34,02:57.0,10.144000,27,THIRION,R‚mi
34,35,145,REVELLI Loris,CANYON COLLECTIVE PIRELLI,10009443942,ITA,1997,60.067,14,0:47.543,...,44,2:00.660,37,2:29.293,36,02:57.0,10.196000,26,REVELLI,Loris
35,36,102,CHAELET Simon,NaN,10071553749,FRA,2002,61.155,4,0:47.759,...,40,2:00.786,38,2:29.685,38,02:58.0,10.959000,25,CHAELET,Simon
36,37,92,VIEIRA Roger,NaN,10009164258,BRA,1994,57.816,43,0:47.577,...,42,2:00.026,32,2:29.163,35,02:58.0,10.960000,24,VIEIRA,Roger
37,38,35,WILLIAMSON Greg,COMMENCAL / 100%,10006909111,GBR,1992,58.824,25,0:47.480,...,46,2:01.617,45,2:30.070,40,02:58.0,11.148000,23,WILLIAMSON,Greg
38,39,89,O CALLAGHAN Oisin,YT RACING DUDES,10017486353,IRL,2003,56.902,49,0:47.354,...,39,2:01.237,41,2:29.612,37,02:58.0,11.257000,22,O,CALLAGHAN Oisin
39,40,1,WALLACE Mark,CANYON COLLECTIVE FACTORY TEAM,10008172636,CAN,1995,58.315,33,0:47.810,...,41,2:01.158,40,2:29.748,39,02:59.0,11.358000,21,WALLACE,Mark
40,41,27,MACDONALD Brook,MS MONDRAKER TEAM,10006429969,NZL,1991,59.801,18,0:46.988,...,28,2:00.594,36,2:30.234,41,02:59.0,11.801000,20,MACDONALD,Brook
41,42,45,DOOLEY Austin,COMMENCAL NORTH AMERICA,10087908151,USA,2002,56.426,51,0:47.477,...,47,2:01.415,42,2:30.993,44,02:59.0,12.282000,19,DOOLEY,Austin
42,43,71,ROGGE Antoine,NaN,10078163590,FRA,2002,57.569,47,0:47.060,...,48,2:01.552,43,2:30.716,43,03:00.0,12.389000,18,ROGGE,Antoine
43,44,37,SLACK Dan,SR SUNTOUR COMMENCAL BY GRAVITY,10088103464,GBR,2002,57.878,40,0:47.388,...,45,2:01.591,44,2:30.696,42,03:00.0,12.630000,17,SLACK,Dan
44,45,41,SILVA Dante,CANYON COLLECTIVE PIRELLI,10071893653,USA,2002,58.824,25,0:47.133,...,36,2:02.524,48,2:32.376,49,03:00.0,13.228000,16,SILVA,Dante
45,46,50,GARCIN Johan,VVRACING ACADEMY,10056657377,FRA,2002,57.816,43,0:49.074,...,50,2:02.469,47,2:31.766,46,03:01.0,13.567000,15,GARCIN,Johan
46,47,55,LALY Thibault,PINKBIKE RACING,10009533464,FRA,1997,60.674,7,0:48.082,...,49,2:01.930,46,2:31.305,45,03:01.0,13.723000,14,LALY,Thibault
47,48,54,MASTERS Edward,PIVOT FACTORY RACING,10005560003,NZL,1989,60.134,13,0:48.935,...,53,2:02.880,49,2:32.162,47,03:01.0,13.873000,13,MASTERS,Edward
48,49,125,GIRONDE Mael,NaN,10074421616,FRA,2003,55.498,55,0:47.858,...,51,2:03.194,51,2:32.554,51,03:01.0,14.152000,12,GIRONDE,Mael
49,50,62,BARANEK Rastislav,NaN,10008169808,SVK,1995,57.816,43,0:48.528,...,52,2:02.993,50,2:32.254,48,03:02.0,14.860000,11,BARANEK,Rastislav
50,51,126,READING Jack,SR SUNTOUR COMMENCAL BY GRAVITY,10006576176,GBR,1988,56.902,49,0:51.154,...,54,2:06.334,53,2:37.178,53,03:07.0,19.842000,10,READING,Jack
51,52,44,EDMONDSON Jamie,ROCKSHOX TREK RACE TEAM,10023865620,GBR,2001,57.631,46,0:47.074,...,56,2:08.179,54,2:38.636,54,03:08.0,20.973000,9,EDMONDSON,Jamie
52,53,121,MAES Martin,NaN,10009453945,BEL,1997,60.067,14,1:04.472,...,57,2:16.784,55,2:44.163,55,03:12.0,24.660000,8,MAES,Martin
53,54,28,ALAZZARI Davide,RRT ROGUE RACING - AFTER SKULL TEAM,10010022205,ITA,1995,56.191,53,1:06.195,...,58,2:20.699,56,2:49.957,56,03:19.0,31.981000,7,ALAZZARI,Davide
54,55,63,BANDEIRA Gon‡alo,NaN,10054661096,POR,2002,54.878,56,0:46.359,...,37,2:24.409,57,2:53.155,57,03:24.0,36.515000,6,BANDEIRA,Gon‡alo
55,56,69,MENOYO BUSQUETS au,COMMENCAL - SCHWALBE,10079233725,ESP,2003,30.647,60,0:47.228,...,31,2:00.486,35,2:32.478,50,03:25.0,37.475000,5,MENOYO,BUSQUETS au
56,57,39,KERR Henry,PROPAIN FACTORY RACING,10111341129,IRL,2000,48.693,59,0:46.709,...,55,2:04.920,52,2:34.823,52,03:26.0,38.292000,4,KERR,Henry
57,58,34,HARRISON Charlie,TREK FACTORY RACING DH,10009645925,USA,1997,57.143,48,0:46.186,...,60,2:26.940,59,2:56.576,58,03:26.0,39.100000,3,HARRISON,Charlie
58,59,2,DAPRELA Thibaut,COMMENCAL/MUC-OFF BY RIDING,10072798480,FRA,2001,52.529,57,0:45.056,...,8,2:25.252,58,3:08.088,59,03:44.0,56.873000,2,DAPRELA,Thibaut
59,60,60,FAIRCLOUGH Brendan,SCOTT DOWNHILL FACTORY,10003642635,GBR,1988,49.180,58,0:52.845,...,59,2:46.689,60,3:37.291,60,04:15.0,0.001016,1,FAIRCLOUGH,Brendan

In [64]:
# Standarise the string format

race_times['last_name'] = race_times['last_name'].str.title()

In [66]:
race_times = race_times.drop(['name'], axis=1)
race_times

,position,world_ranking,team,uci_number,nationality,yob,speed,speed_ranking,split_1,split_1_pos,...,split_2_pos,split_3,split_3_pos,split_4,split_4_pos,time,tow,points,last_name,first_name
0,1,6,COMMENCAL/MUC-OFF BY RIDING,10008827283,FRA,1996,60.335,11,0:44.269,1,...,7,1:53.519,1,2:20.293,1,02:47.0,0.000000,200,Ierron,Amaury
1,2,14,SPECIALIZED GRAVITY,10090907774,CAN,1999,59.081,21,0:44.924,2,...,1,1:53.573,2,2:20.354,2,02:48.0,0.847000,160,Iles,Finn
2,3,1,SPECIALIZED GRAVITY,10007544358,FRA,1994,58.824,25,0:45.023,4,...,3,1:53.788,3,2:20.960,3,02:48.0,1.086000,140,Bruni,Loic
3,4,8,DORVAL AM COMMENCAL,10008194359,FRA,1994,59.081,21,0:45.302,7,...,5,1:54.638,6,2:21.349,4,02:49.0,1.466000,125,Coulanges,Benoit
4,5,17,CANYON COLLECTIVE FACTORY TEAM,10008813442,USA,1996,61.224,3,0:45.223,6,...,4,1:54.231,4,2:21.860,5,02:50.0,2.431000,110,Shaw,Luca
5,6,9,CUBE FACTORY RACING,10005470073,GBR,1991,60.067,14,0:46.511,21,...,12,1:54.979,7,2:22.370,6,02:50.0,2.695000,95,Hart,Danny
6,7,5,TREK FACTORY RACING DH,10009563271,GBR,1996,60.335,11,0:45.689,9,...,6,1:54.377,5,2:22.392,7,02:51.0,3.373000,90,Wilson,Reece
7,8,7,SANTA CRUZ SYNDICATE,10009404738,GBR,1997,58.127,36,0:45.453,8,...,9,1:56.086,8,2:23.325,8,02:51.0,3.856000,85,Greenland,Laurie
8,9,64,COMMENCAL LES ORRES,10070590924,FRA,2001,57.878,40,0:46.027,14,...,15,1:56.199,9,2:23.371,9,02:51.0,4.160000,80,Vidal,Antoine
9,10,1,MADISON SARACEN FACTORY TEAM,10011016756,GBR,1999,61.714,2,0:46.072,15,...,11,1:56.357,10,2:23.966,10,02:52.0,4.463000,75,Walker,Matt
10,11,1,INTENSE FACTORY RACING,10010038167,USA,1992,61.155,4,0:46.652,23,...,21,1:57.219,12,2:24.453,11,02:52.0,5.219000,70,Norton,Dakotah
11,12,3,TREK FACTORY RACING DH,10008723112,FRA,1996,59.081,21,0:45.003,3,...,2,1:57.561,14,2:24.706,12,02:53.0,5.414000,65,Vergier,Loris
12,13,30,TREK FACTORY RACING DH,10023896336,GBR,2000,58.065,38,0:47.053,34,...,24,1:58.072,18,2:26.002,15,02:54.0,6.362000,60,Edwards,Kade
13,14,1,COMMENCAL / 100%,10008831529,ESP,1995,58.315,33,0:46.381,19,...,17,1:57.803,16,2:25.928,14,02:54.0,6.561000,55,Suarez,ALONSO Ange
14,15,2,CUBE FACTORY RACING,10011213584,GER,1999,59.276,20,0:45.839,11,...,13,1:57.233,13,2:25.913,13,02:54.0,6.851000,50,Hartenstern,Max
15,16,1,SANTA CRUZ SYNDICATE,10002818640,RSA,1981,58.315,33,0:45.994,13,...,19,1:57.850,17,2:26.252,16,02:55.0,7.456000,45,Minnaar,Greg
16,17,109,COMMENCAL / 100%,10016018118,FRA,1999,58.065,38,0:46.739,27,...,16,1:56.962,11,2:26.290,17,02:55.0,7.665000,44,Frixtalon,Hugo
17,18,1,MS MONDRAKER TEAM,10007713403,AUT,1994,58.824,25,0:46.632,22,...,25,1:58.839,26,2:26.901,20,02:55.0,7.734000,43,Trummer,David
18,19,93,SORTED RACEGEAR,10008728667,GBR,1996,56.426,51,0:47.705,48,...,43,1:59.479,27,2:27.393,24,02:55.0,8.010000,42,Vernon,Taylor
19,20,22,PIVOT FACTORY RACING,10006413094,GBR,1991,58.824,25,0:46.435,20,...,14,1:57.740,15,2:26.432,18,02:55.0,8.159000,41,Kerr,Bernard
20,21,53,PROPAIN FACTORY RACING,10049212326,AUS,2002,60.403,10,0:46.984,30,...,27,1:58.301,20,2:26.836,19,02:55.0,8.219000,40,Meier-Smith,Luke
21,22,21,CONTINENTAL ATHERTON,10009187092,AUT,1996,58.568,31,0:46.994,32,...,23,1:58.658,23,2:26.971,22,02:56.0,8.311000,39,Kolb,Andreas
22,23,23,CONTINENTAL ATHERTON,10009897014,GBR,1998,57.878,40,0:46.661,24,...,26,1:58.645,22,2:26.911,21,02:56.0,8.513000,38,Hatton,Charlie
23,24,1,DORVAL AM COMMENCAL,10008586504,FRA,1993,56.191,53,0:47.016,33,...,22,1:58.813,25,2:27.133,23,02:56.0,9.122000,37,Ierron,Baptiste
24,25,31,SCOTT DOWNHILL FACTORY,10008831731,FRA,1996,59.801,18,0:45.933,12,...,18,1:58.417,21,2:27.941,27,02:56.0,9.261000,36,Levesque,Dylan
25,26,24,SCOTT DOWNHILL FACTORY,10008103322,AUS,1995,60.674,7,0:45.815,10,...,10,1:58.784,24,2:27.890,25,02:57.0,9.347000,35,Lucas,Dean
26,27,40,MS MONDRAKER TEAM,10009453642,IRL,1997,60.067,14,0:47.191,38,...,34,1:59.984,30,2:28.116,28,02:57.0,9.422000,34,Dickson,Jacob
27,28,51,COMMENCAL / 100%,10008848505,FRA,1996,58.824,25,0:47.198,39,...,29,1:59.502,28,2:28.182,29,02:57.0,9.605000,33,Estaque,Thomas
28,29,43,FORBIDDEN SYNTHESIS TEAM,10007656314,AUS,1994,60.606,9,0:46.284,17,...,20,1:58.299,19,2:27.924,26,02:57.0,9.843000,32,Fearon,Connor
29,30,118,NaN,10007714413,FRA,1994,61.998,1,0:46.685,25,...,32,2:00.185,33,2:28.697,32,02:57.0,9.939000,31,Cabirou,Rudy
30,31,97,CANYON COLLECTIVE FMD,10061876381,GBR,2003,58.127,36,0:46.905,28,...,30,1:59.874,29,2:28.425,30,02:57.0,9.941000,30,Luffman,Dennis
31,32,143,NaN,10009562968,FRA,1996,59.081,21,0:47.240,41,...,38,2:00.001,31,2:28.447,31,02:57.0,9.990000,29,Dailly,Adrien
32,33,75,INTENSE FACTORY RACING,10006516663,USA,1987,60.879,6,0:46.912,29,...,33,2:00.193,34,2:28.752,33,02:57.0,10.084000,28,Gwin,Aaron
33,34,1,GIANT FACTORY OFF - ROAD TEAM,10005415715,FRA,1990,58.568,31,0:47.909,52,...,35,2:00.827,39,2:28.808,34,02:57.0,10.144000,27,Thirion,R‚mi
34,35,145,CANYON COLLECTIVE PIRELLI,10009443942,ITA,1997,60.067,14,0:47.543,46,...,44,2:00.660,37,2:29.293,36,02:57.0,10.196000,26,Revelli,Loris
35,36,102,NaN,10071553749,FRA,2002,61.155,4,0:47.759,49,...,40,2:00.786,38,2:29.685,38,02:58.0,10.959000,25,Chaelet,Simon
36,37,92,NaN,10009164258,BRA,1994,57.816,43,0:47.577,47,...,42,2:00.026,32,2:29.163,35,02:58.0,10.960000,24,Vieira,Roger
37,38,35,COMMENCAL / 100%,10006909111,GBR,1992,58.824,25,0:47.480,45,...,46,2:01.617,45,2:30.070,40,02:58.0,11.148000,23,Williamson,Greg
38,39,89,YT RACING DUDES,10017486353,IRL,2003,56.902,49,0:47.354,42,...,39,2:01.237,41,2:29.612,37,02:58.0,11.257000,22,O,CALLAGHAN Oisin
39,40,1,CANYON COLLECTIVE FACTORY TEAM,10008172636,CAN,1995,58.315,33,0:47.810,50,...,41,2:01.158,40,2:29.748,39,02:59.0,11.358000,21,Wallace,Mark
40,41,27,MS MONDRAKER TEAM,10006429969,NZL,1991,59.801,18,0:46.988,31,...,28,2:00.594,36,2:30.234,41,02:59.0,11.801000,20,Macdonald,Brook
41,42,45,COMMENCAL NORTH AMERICA,10087908151,USA,2002,56.426,51,0:47.477,44,...,47,2:01.415,42,2:30.993,44,02:59.0,12.282000,19,Dooley,Austin
42,43,71,NaN,10078163590,FRA,2002,57.569,47,0:47.060,35,...,48,2:01.552,43,2:30.716,43,03:00.0,12.389000,18,Rogge,Antoine
43,44,37,SR SUNTOUR COMMENCAL BY GRAVITY,10088103464,GBR,2002,57.878,40,0:47.388,43,...,45,2:01.591,44,2:30.696,42,03:00.0,12.630000,17,Slack,Dan
44,45,41,CANYON COLLECTIVE PIRELLI,10071893653,USA,2002,58.824,25,0:47.133,37,...,36,2:02.524,48,2:32.376,49,03:00.0,13.228000,16,Silva,Dante
45,46,50,VVRACING ACADEMY,10056657377,FRA,2002,57.816,43,0:49.074,56,...,50,2:02.469,47,2:31.766,46,03:01.0,13.567000,15,Garcin,Johan
46,47,55,PINKBIKE RACING,10009533464,FRA,1997,60.674,7,0:48.082,53,...,49,2:01.930,46,2:31.305,45,03:01.0,13.723000,14,Laly,Thibault
47,48,54,PIVOT FACTORY RACING,10005560003,NZL,1989,60.134,13,0:48.935,55,...,53,2:02.880,49,2:32.162,47,03:01.0,13.873000,13,Masters,Edward
48,49,125,NaN,10074421616,FRA,2003,55.498,55,0:47.858,51,...,51,2:03.194,51,2:32.554,51,03:01.0,14.152000,12,Gironde,Mael
49,50,62,NaN,10008169808,SVK,1995,57.816,43,0:48.528,54,...,52,2:02.993,50,2:32.254,48,03:02.0,14.860000,11,Baranek,Rastislav
50,51,126,SR SUNTOUR COMMENCAL BY GRAVITY,10006576176,GBR,1988,56.902,49,0:51.154,57,...,54,2:06.334,53,2:37.178,53,03:07.0,19.842000,10,Reading,Jack
51,52,44,ROCKSHOX TREK RACE TEAM,10023865620,GBR,2001,57.631,46,0:47.074,36,...,56,2:08.179,54,2:38.636,54,03:08.0,20.973000,9,Edmondson,Jamie
52,53,121,NaN,10009453945,BEL,1997,60.067,14,1:04.472,59,...,57,2:16.784,55,2:44.163,55,03:12.0,24.660000,8,Maes,Martin
53,54,28,RRT ROGUE RACING - AFTER SKULL TEAM,10010022205,ITA,1995,56.191,53,1:06.195,60,...,58,2:20.699,56,2:49.957,56,03:19.0,31.981000,7,Alazzari,Davide
54,55,63,NaN,10054661096,POR,2002,54.878,56,0:46.359,18,...,37,2:24.409,57,2:53.155,57,03:24.0,36.515000,6,Bandeira,Gon‡alo
55,56,69,COMMENCAL - SCHWALBE,10079233725,ESP,2003,30.647,60,0:47.228,40,...,31,2:00.486,35,2:32.478,50,03:25.0,37.475000,5,Menoyo,BUSQUETS au
56,57,39,PROPAIN FACTORY RACING,10111341129,IRL,2000,48.693,59,0:46.709,26,...,55,2:04.920,52,2:34.823,52,03:26.0,38.292000,4,Kerr,Henry
57,58,34,TREK FACTORY RACING DH,10009645925,USA,1997,57.143,48,0:46.186,16,...,60,2:26.940,59,2:56.576,58,03:26.0,39.100000,3,Harrison,Charlie
58,59,2,COMMENCAL/MUC-OFF BY RIDING,10072798480,FRA,2001,52.529,57,0:45.056,5,...,8,2:25.252,58,3:08.088,59,03:44.0,56.873000,2,Daprela,Thibaut
59,60,60,SCOTT DOWNHILL FACTORY,10003642635,GBR,1988,49.180,58,0:52.845,58,...,59,2:46.689,60,3:37.291,60,04:15.0,0.001016,1,Fairclough,Brendan

In [67]:
race_times.dtypes

position          object
world_ranking      int64
team              object
uci_number         int64
nationality       object
yob                int64
speed            float64
speed_ranking      int64
split_1           object
split_1_pos        int64
split_2           object
split_2_pos        int64
split_3           object
split_3_pos        int64
split_4           object
split_4_pos        int64
time              object
tow              float64
points             int64
last_name         object
first_name        object
dtype: object

In [69]:
race_times.describe(include='all')

,position,world_ranking,team,uci_number,nationality,yob,speed,speed_ranking,split_1,split_1_pos,...,split_2_pos,split_3,split_3_pos,split_4,split_4_pos,time,tow,points,last_name,first_name
count,60,60.00000,51,6.000000e+01,60,60.000000,60.000000,60.000000,60,60.000000,...,60.000000,60,60.000000,60,60.000000,60,60.000000,60.000000,60,60
unique,60,NaN,29,NaN,16,NaN,NaN,NaN,60,NaN,...,NaN,60,NaN,60,NaN,25,NaN,NaN,58,56
top,1,NaN,COMMENCAL / 100%,NaN,FRA,NaN,NaN,NaN,0:44.269,NaN,...,NaN,1:53.519,NaN,2:20.293,NaN,02:57.0,NaN,NaN,Ierron,Greg
freq,1,NaN,4,NaN,18,NaN,NaN,NaN,1,NaN,...,NaN,1,NaN,1,NaN,10,NaN,NaN,2,2
mean,NaN,45.55000,NaN,1.002561e+10,NaN,1996.383333,57.900883,29.733333,NaN,30.500000,...,30.500000,NaN,30.500000,NaN,30.500000,NaN,12.160734,41.583333,NaN,NaN
std,NaN,40.98343,NaN,2.978446e+07,NaN,4.679894,4.354411,17.561385,NaN,17.464249,...,17.464249,NaN,17.464249,NaN,17.464249,NaN,10.786813,40.167991,NaN,NaN
min,NaN,1.00000,NaN,1.000282e+10,NaN,1981.000000,30.647000,1.000000,NaN,1.000000,...,1.000000,NaN,1.000000,NaN,1.000000,NaN,0.000000,1.000000,NaN,NaN
25%,NaN,7.75000,NaN,1.000815e+10,NaN,1994.000000,57.769750,14.000000,NaN,15.750000,...,15.750000,NaN,15.750000,NaN,15.750000,NaN,6.778500,15.750000,NaN,NaN
50%,NaN,38.00000,NaN,1.000945e+10,NaN,1996.000000,58.696000,28.000000,NaN,30.500000,...,30.500000,NaN,30.500000,NaN,30.500000,NaN,9.891000,30.500000,NaN,NaN
75%,NaN,65.25000,NaN,1.003023e+10,NaN,2000.250000,60.067000,43.750000,NaN,45.250000,...,45.250000,NaN,45.250000,NaN,45.250000,NaN,12.779500,46.250000,NaN,NaN
max,NaN,145.00000,NaN,1.011134e+10,NaN,2003.000000,61.998000,60.000000,NaN,60.000000,...,60.000000,NaN,60.000000,NaN,60.000000,NaN,56.873000,200.000000,NaN,NaN

In [70]:
# Examine the unqiue values in 'team' and check for NA values

race_times['team'].unique()

# Blank values are stored as nan

array(['COMMENCAL/MUC-OFF BY RIDING', 'SPECIALIZED GRAVITY',
       'DORVAL AM COMMENCAL', 'CANYON COLLECTIVE FACTORY TEAM',
       'CUBE FACTORY RACING', 'TREK FACTORY RACING DH',
       'SANTA CRUZ SYNDICATE', 'COMMENCAL LES ORRES',
       'MADISON SARACEN FACTORY TEAM', 'INTENSE FACTORY RACING',
       'COMMENCAL / 100%', 'MS MONDRAKER TEAM', 'SORTED RACEGEAR',
       'PIVOT FACTORY RACING', 'PROPAIN FACTORY RACING',
       'CONTINENTAL ATHERTON', 'SCOTT DOWNHILL FACTORY',
       'FORBIDDEN SYNTHESIS TEAM', nan, 'CANYON COLLECTIVE FMD',
       'GIANT FACTORY OFF - ROAD TEAM', 'CANYON COLLECTIVE PIRELLI',
       'YT RACING DUDES', 'COMMENCAL NORTH AMERICA',
       'SR SUNTOUR COMMENCAL BY GRAVITY', 'VVRACING ACADEMY',
       'PINKBIKE RACING', 'ROCKSHOX TREK RACE TEAM',
       'RRT ROGUE RACING - AFTER SKULL TEAM', 'COMMENCAL - SCHWALBE'],
      dtype=object)

In [80]:
# Replace nan values with pandas recognised format

race_times['team'] = np.where(race_times['team']=='nan', pd.NA, race_times['team'])

race_times['team'].unique()

# np.where() did not pick up nan values as a string

array(['COMMENCAL/MUC-OFF BY RIDING', 'SPECIALIZED GRAVITY',
       'DORVAL AM COMMENCAL', 'CANYON COLLECTIVE FACTORY TEAM',
       'CUBE FACTORY RACING', 'TREK FACTORY RACING DH',
       'SANTA CRUZ SYNDICATE', 'COMMENCAL LES ORRES',
       'MADISON SARACEN FACTORY TEAM', 'INTENSE FACTORY RACING',
       'COMMENCAL / 100%', 'MS MONDRAKER TEAM', 'SORTED RACEGEAR',
       'PIVOT FACTORY RACING', 'PROPAIN FACTORY RACING',
       'CONTINENTAL ATHERTON', 'SCOTT DOWNHILL FACTORY',
       'FORBIDDEN SYNTHESIS TEAM', nan, 'CANYON COLLECTIVE FMD',
       'GIANT FACTORY OFF - ROAD TEAM', 'CANYON COLLECTIVE PIRELLI',
       'YT RACING DUDES', 'COMMENCAL NORTH AMERICA',
       'SR SUNTOUR COMMENCAL BY GRAVITY', 'VVRACING ACADEMY',
       'PINKBIKE RACING', 'ROCKSHOX TREK RACE TEAM',
       'RRT ROGUE RACING - AFTER SKULL TEAM', 'COMMENCAL - SCHWALBE'],
      dtype=object)

In [78]:
# Check to see if nan values are present in 'team'

race_times.isna().sum()

position         0
world_ranking    0
team             9
uci_number       0
nationality      0
yob              0
speed            0
speed_ranking    0
split_1          0
split_1_pos      0
split_2          0
split_2_pos      0
split_3          0
split_3_pos      0
split_4          0
split_4_pos      0
time             0
tow              0
points           0
last_name        0
first_name       0
dtype: int64

In [81]:
# Cast all values in the 'team' to be a string

race_times['team'] = race_times['team'].astype(str)

In [83]:
race_times['team'] = np.where(race_times['team']=='nan', pd.NA, race_times['team'])

race_times['team'].unique()

array(['COMMENCAL/MUC-OFF BY RIDING', 'SPECIALIZED GRAVITY',
       'DORVAL AM COMMENCAL', 'CANYON COLLECTIVE FACTORY TEAM',
       'CUBE FACTORY RACING', 'TREK FACTORY RACING DH',
       'SANTA CRUZ SYNDICATE', 'COMMENCAL LES ORRES',
       'MADISON SARACEN FACTORY TEAM', 'INTENSE FACTORY RACING',
       'COMMENCAL / 100%', 'MS MONDRAKER TEAM', 'SORTED RACEGEAR',
       'PIVOT FACTORY RACING', 'PROPAIN FACTORY RACING',
       'CONTINENTAL ATHERTON', 'SCOTT DOWNHILL FACTORY',
       'FORBIDDEN SYNTHESIS TEAM', <NA>, 'CANYON COLLECTIVE FMD',
       'GIANT FACTORY OFF - ROAD TEAM', 'CANYON COLLECTIVE PIRELLI',
       'YT RACING DUDES', 'COMMENCAL NORTH AMERICA',
       'SR SUNTOUR COMMENCAL BY GRAVITY', 'VVRACING ACADEMY',
       'PINKBIKE RACING', 'ROCKSHOX TREK RACE TEAM',
       'RRT ROGUE RACING - AFTER SKULL TEAM', 'COMMENCAL - SCHWALBE'],
      dtype=object)

In [84]:
race_times.head()

,position,world_ranking,team,uci_number,nationality,yob,speed,speed_ranking,split_1,split_1_pos,...,split_2_pos,split_3,split_3_pos,split_4,split_4_pos,time,tow,points,last_name,first_name
0,1,6,COMMENCAL/MUC-OFF BY RIDING,10008827283,FRA,1996,60.335,11,0:44.269,1,...,7,1:53.519,1,2:20.293,1,02:47.0,0.000,200,Ierron,Amaury
1,2,14,SPECIALIZED GRAVITY,10090907774,CAN,1999,59.081,21,0:44.924,2,...,1,1:53.573,2,2:20.354,2,02:48.0,0.847,160,Iles,Finn
2,3,1,SPECIALIZED GRAVITY,10007544358,FRA,1994,58.824,25,0:45.023,4,...,3,1:53.788,3,2:20.960,3,02:48.0,1.086,140,Bruni,Loic
3,4,8,DORVAL AM COMMENCAL,10008194359,FRA,1994,59.081,21,0:45.302,7,...,5,1:54.638,6,2:21.349,4,02:49.0,1.466,125,Coulanges,Benoit
4,5,17,CANYON COLLECTIVE FACTORY TEAM,10008813442,USA,1996,61.224,3,0:45.223,6,...,4,1:54.231,4,2:21.860,5,02:50.0,2.431,110,Shaw,Luca

In [89]:
# uci number is a unqiue identifier, does not need to have numeric operations performed on it 

race_times['uci_number'] = race_times['uci_number'].astype(str)
race_times['nationality'] = race_times['nationality'].astype(str)

In [100]:
# change 'yob' to be a recognised year in date-time format
race_times['yob'] = race_times['yob'].astype(str)

race_times['yob'] = pd.to_datetime(race_times['yob'], format='%Y')

In [102]:
race_times.dtypes

position                 object
world_ranking             int64
team                     object
uci_number               object
nationality              object
yob              datetime64[ns]
speed                   float64
speed_ranking             int64
split_1                  object
split_1_pos               int64
split_2                  object
split_2_pos               int64
split_3                  object
split_3_pos               int64
split_4                  object
split_4_pos               int64
time                     object
tow                     float64
points                    int64
last_name                object
first_name               object
dtype: object

In [104]:
# Change all split times into date time format

race_times['split_1'] = pd.to_datetime(race_times['split_1'], format='%M:%S.%f')
race_times['split_2'] = pd.to_datetime(race_times['split_2'], format='%M:%S.%f')
race_times['split_3'] = pd.to_datetime(race_times['split_3'], format='%M:%S.%f')
race_times['split_4'] = pd.to_datetime(race_times['split_4'], format='%M:%S.%f')

In [105]:
race_times.head()

,position,world_ranking,team,uci_number,nationality,yob,speed,speed_ranking,split_1,split_1_pos,...,split_2_pos,split_3,split_3_pos,split_4,split_4_pos,time,tow,points,last_name,first_name
0,1,6,COMMENCAL/MUC-OFF BY RIDING,10008827283,FRA,1996-01-01,60.335,11,1900-01-01 00:00:44.269,1,...,7,1900-01-01 00:01:53.519,1,1900-01-01 00:02:20.293,1,02:47.0,0.000,200,Ierron,Amaury
1,2,14,SPECIALIZED GRAVITY,10090907774,CAN,1999-01-01,59.081,21,1900-01-01 00:00:44.924,2,...,1,1900-01-01 00:01:53.573,2,1900-01-01 00:02:20.354,2,02:48.0,0.847,160,Iles,Finn
2,3,1,SPECIALIZED GRAVITY,10007544358,FRA,1994-01-01,58.824,25,1900-01-01 00:00:45.023,4,...,3,1900-01-01 00:01:53.788,3,1900-01-01 00:02:20.960,3,02:48.0,1.086,140,Bruni,Loic
3,4,8,DORVAL AM COMMENCAL,10008194359,FRA,1994-01-01,59.081,21,1900-01-01 00:00:45.302,7,...,5,1900-01-01 00:01:54.638,6,1900-01-01 00:02:21.349,4,02:49.0,1.466,125,Coulanges,Benoit
4,5,17,CANYON COLLECTIVE FACTORY TEAM,10008813442,USA,1996-01-01,61.224,3,1900-01-01 00:00:45.223,6,...,4,1900-01-01 00:01:54.231,4,1900-01-01 00:02:21.860,5,02:50.0,2.431,110,Shaw,Luca

In [109]:
# Change final time to date time format

race_times['time'] = pd.to_datetime(race_times['time'], format='%M:%S.%f')

In [110]:
# Cast time off winner to a string then convert to date time format

race_times['tow'] = race_times['tow'].astype(str)
race_times['tow'] = pd.to_datetime(race_times['tow'], format='%S.%f')

In [111]:
race_times.head()

,position,world_ranking,team,uci_number,nationality,yob,speed,speed_ranking,split_1,split_1_pos,...,split_2_pos,split_3,split_3_pos,split_4,split_4_pos,time,tow,points,last_name,first_name
0,1,6,COMMENCAL/MUC-OFF BY RIDING,10008827283,FRA,1996-01-01,60.335,11,1900-01-01 00:00:44.269,1,...,7,1900-01-01 00:01:53.519,1,1900-01-01 00:02:20.293,1,1900-01-01 00:02:47,1900-01-01 00:00:00.000,200,Ierron,Amaury
1,2,14,SPECIALIZED GRAVITY,10090907774,CAN,1999-01-01,59.081,21,1900-01-01 00:00:44.924,2,...,1,1900-01-01 00:01:53.573,2,1900-01-01 00:02:20.354,2,1900-01-01 00:02:48,1900-01-01 00:00:00.847,160,Iles,Finn
2,3,1,SPECIALIZED GRAVITY,10007544358,FRA,1994-01-01,58.824,25,1900-01-01 00:00:45.023,4,...,3,1900-01-01 00:01:53.788,3,1900-01-01 00:02:20.960,3,1900-01-01 00:02:48,1900-01-01 00:00:01.086,140,Bruni,Loic
3,4,8,DORVAL AM COMMENCAL,10008194359,FRA,1994-01-01,59.081,21,1900-01-01 00:00:45.302,7,...,5,1900-01-01 00:01:54.638,6,1900-01-01 00:02:21.349,4,1900-01-01 00:02:49,1900-01-01 00:00:01.466,125,Coulanges,Benoit
4,5,17,CANYON COLLECTIVE FACTORY TEAM,10008813442,USA,1996-01-01,61.224,3,1900-01-01 00:00:45.223,6,...,4,1900-01-01 00:01:54.231,4,1900-01-01 00:02:21.860,5,1900-01-01 00:02:50,1900-01-01 00:00:02.431,110,Shaw,Luca

In [116]:
# Adding name identifiter of race and category

race_times['race_name'] = 'Lourdes Mens Elite'

In [118]:
race_times['race_date'] = pd.to_datetime('2022-03-27')

In [119]:
race_times.head()

,position,world_ranking,team,uci_number,nationality,yob,speed,speed_ranking,split_1,split_1_pos,...,split_3_pos,split_4,split_4_pos,time,tow,points,last_name,first_name,race_name,race_date
0,1,6,COMMENCAL/MUC-OFF BY RIDING,10008827283,FRA,1996-01-01,60.335,11,1900-01-01 00:00:44.269,1,...,1,1900-01-01 00:02:20.293,1,1900-01-01 00:02:47,1900-01-01 00:00:00.000,200,Ierron,Amaury,Lourdes Mens Elite,2022-03-27
1,2,14,SPECIALIZED GRAVITY,10090907774,CAN,1999-01-01,59.081,21,1900-01-01 00:00:44.924,2,...,2,1900-01-01 00:02:20.354,2,1900-01-01 00:02:48,1900-01-01 00:00:00.847,160,Iles,Finn,Lourdes Mens Elite,2022-03-27
2,3,1,SPECIALIZED GRAVITY,10007544358,FRA,1994-01-01,58.824,25,1900-01-01 00:00:45.023,4,...,3,1900-01-01 00:02:20.960,3,1900-01-01 00:02:48,1900-01-01 00:00:01.086,140,Bruni,Loic,Lourdes Mens Elite,2022-03-27
3,4,8,DORVAL AM COMMENCAL,10008194359,FRA,1994-01-01,59.081,21,1900-01-01 00:00:45.302,7,...,6,1900-01-01 00:02:21.349,4,1900-01-01 00:02:49,1900-01-01 00:00:01.466,125,Coulanges,Benoit,Lourdes Mens Elite,2022-03-27
4,5,17,CANYON COLLECTIVE FACTORY TEAM,10008813442,USA,1996-01-01,61.224,3,1900-01-01 00:00:45.223,6,...,4,1900-01-01 00:02:21.860,5,1900-01-01 00:02:50,1900-01-01 00:00:02.431,110,Shaw,Luca,Lourdes Mens Elite,2022-03-27